# Generated by Django 4.2 on 2023-04-22 09:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("city_coordinates", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="coordinates",
            field=django.contrib.gis.db.models.fields.PointField(
                srid=4326, verbose_name="Координаты"
            ),
        ),
    ]
