# Generated by Django 4.2 on 2023-04-23 05:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("city_coordinates", "0002_alter_city_coordinates"),
    ]

    operations = [
        migrations.RenameField(
            model_name="city",
            old_name="coordinates",
            new_name="location",
        ),
    ]
